Servers = ["192.168.1.36"]
printers = ["Samsung-UpOffice",
"Samsung-Tirat-Carmel",
"Samsung-Starter",
"Samsung-Stanley-Migdal",
"Samsung-Sherut3",
"Samsung-Sachar2",
"Samsung-Ramle",
"Samsung-Rahat",
"Samsung-Project",
"Samsung-Natany-Olim",
"Samsung-Mechirot",
"Samsung-Mazkira",
"Samsung-Mate-Hadash",
"Samsung-Lapid.Ashkelon",
"Samsung-Klita-Naharya",
"Samsung-Kiryat-Gat",
"Samsung-Holon-Starter",
"Samsung-hinuch-office",
"Samsung-H.R.migdal-haemeq",
"Samsung-H.R.Hadera",
"Samsung-H.R.Hadar",
"Samsung-H.R-TveryaNew",
"Samsung-H.R-Sherut2",
"Samsung-H.R-Sherut",
"Samsung-H.R-Rishon",
"Samsung-H.R-Rachely",
"Samsung-H.R-PetachTikva",
"Samsung-H.R-Office-Hifa",
"Samsung-H.R-Nazeret",
"Samsung-H.R-Natanya",
"Samsung-H.R-Nahariya",
"Samsung-H.R-Loud",
"Samsung-H.R-Huzot-Pro",
"Samsung-H.R-Holon",
"Samsung-H.R-Carmiel-Pro",
"Samsung-H.R-Carmiel",
"Samsung-H.R-BerSheva",
"Samsung-H.R-Ashdod",
"Samsung-H.R-Akko",
"Samsung-H.R-Afula2",
"Samsung-H.R-Afula",
"Samsung-Gilads",
"Samsung-G.R-MateTira",
"Samsung-G.R-IsraelaC",
"Samsung-Finance",
"Samsung-Exceutive",
"Samsung-CPS-Floor2",
"Samsung-CPS-Floor1",
"Samsung-Batsheva_Sarit",
"Ricoh-MaofProject",
"Rich-H.R.-Rosh-Ayin",
"pscript",
"Microsoft Print to PDF",
"Canon-May",
"Canon-H.R-Tverya",
"Canon-H.R-Rehovot",
"Canon-H.R-Mehcirot-Natanya",
"Brother-Yaele",
"Brother-Manal",
"Brother-Lod",
"Brother-Klita3",
"Brother-israela",
"Brother-Hadas",
"Brother-H.R-Keren",
"Brother-H.R-Jerusalem"
"Brother-G.R-TamarBar"
]

for server in Servers:
    for Printer_Name in printers:
        printerpermission_part1 = r"\\192.168.1.36\c$\Users\Administrator.MAOF-GROUP\Desktop\subinacl /noverbose /output=C:\Users\avihai\Desktop\Test.txt /printer "
        printer = r"\\" + server + "\\" + Printer_Name
        Get_Content = "Get-Content -Path C:\\Users\\avihai\\Desktop\\Test.txt | Add-Content C:\\Users\\avihai\\Desktop\\printers.txt"
        Printer_Get_Permission = printerpermission_part1 + printer
        print(Printer_Get_Permission)
        print(Get_Content)
